# Generated by Django 4.2 on 2024-10-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_studio_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='lasting_hr',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='lasting_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='guests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
