# Generated by Django 4.2 on 2024-10-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_guests_alter_orderitem_lasting_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='related_order_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
